export enum Status {
  Pending = 'Pending',
  Resolved = 'Resolved',
  RequestFinance = 'RequestFinance',
  RequestManager = 'RequestManager',
  Finished = 'Finished',
  Rejected = 'Rejected',
  Payment = 'Payment',
  Reimbursement = 'Reimbursement',
  LEAD = 'LEAD',
  CONVERTEDTOCONTACT = 'CONVERTEDTOCONTACT',
  LOST = 'LOST',
  Active = 'Active',
  Inactive = 'Inactive',
}
